### ISSUE TITLE
Unnecessary files included in the gem

### ISSUE THREAD

**Issue by oturpe** [flori/tins#20]
I am the maintainer of the [rubygem-tins][fedora] package in Fedora.
In the packaging script, we currently remove certain files that are shipped with the tins gem,
because they seem to be for development only
and completely unnecessary at runtime:
`TODO`, `VERSION`, `.all_images.yml`, `.gitignore`, `.tool-versions`.

Removing these during packaging is not a big issue at all, but I wonder, 
would it simply be better to exclude those files from the gem?
What do you think?

[fedora]: https://packages.fedoraproject.org/pkgs/rubygem-tins/rubygem-tins/

**Comment by flori** [comment]
Can you try v1.31.1?

**Comment by oturpe** [comment]
Thank you, the problem is solved!
